"""hashAB tables manifest: name -> (offset, length) in _hashab_tables.bin.

Generated by tools/gen_hashab_tables.py from dstaley/hashab (public domain).
The bytes are loaded by hashab_py.py via importlib.resources.
"""

TABLES = {
    'FINAL_PERM': (0, 220),
    'FINAL_SBOX': (220, 256),
    'GEN190_SBOX': (476, 2048),
    'GEN190_STATE_TABLE': (2524, 2048),
    'IBUFF_KEY_TABLE': (4572, 256),
    'IBUFF_MIX_SEED_A': (4828, 256),
    'IBUFF_MIX_SEED_B': (5084, 256),
    'INPUT_SBOX': (5340, 256),
    'MIXCOL_MULT': (5596, 6144),
    'MIXCOL_STATE': (11740, 4096),
    'NIBBLE_SBOX_EVEN': (15836, 512),
    'NIBBLE_SBOX_MAIN': (16348, 512),
    'NIBBLE_SBOX_ODD': (16860, 512),
    'OUTPUT_SBOX': (17372, 256),
    'ROUND_KEYS': (17628, 176),
    'WB_FINAL_SBOX': (17804, 4096),
    'WB_INPUT_A': (21900, 4096),
    'WB_INPUT_B': (25996, 4096),
    'WB_MIX_A': (30092, 8192),
    'WB_MIX_B': (38284, 8192),
    'WB_STATE_EXTRACT': (46476, 4096),
    'WB_T_MIX': (50572, 245760),
    'WB_T_TABLES': (296332, 147456),
}
