"""Pure-Python cover writer for the iPod nano 7G (without libgpod).

The format was taken from the iTunes reference on the device (native/fixtures/itunes_artwork/):
the nano 7G stores covers in `iPod_Control/Artwork/`:

  - `ArtworkDB` — a binary container of atoms (mhfd → 3×mhsd → mhli/mhla/mhlf).
    The image list (mhsd index=1) contains one `mhii` per track; each
    `mhii` describes 4 thumbnails (per format 1010/1013/1015/1016) via
    mhod(type=2)→mhni→mhod(type=3, file name), plus a service mhod(type=6, mhaf).
  - `F<fmt>_1.ithmb` — raw RGB565-LE frames back to back, `slot` bytes per frame.

Link to the SQLite library: `item.artwork_status=1`,
`item.artwork_cache_id = mhii.image_id`; `mhii.song_id = unsigned(item.pid)`.

The write strategy is a **surgical incremental append**: existing
`mhii` and album/format lists are preserved byte-for-byte, new frames are
appended to the end of `.ithmb`, and a new `mhii` is added to the list. This way we
don't break the 700+ covers already generated by iTunes. `Locations.itdb` is not touched,
so a cbk signature isn't needed.

All structures are little-endian. Offsets were verified against the reference; the atom
templates are real iTunes bytes, we only patch image_id/song_id/ithmb_offset.
"""
from __future__ import annotations

import io
import struct
from dataclasses import dataclass, field
from pathlib import Path

from ._art_templates import (MHFD_TEMPLATE, MHII_HEADER, MHIF_ALL, MHLA_TEMPLATE,
                             MHLF_TEMPLATE, MHLI_TEMPLATE, MHNI, MHOD_CONTAINER,
                             MHOD_MHAF, STRMHOD)

U64 = 1 << 64

# --- nano 7G thumbnail formats (format_id, width, height, slot_bytes) -----------
# slot == width*height*2, except 1016 (57×57=6498, slot 6612 = 57×58: the device
# reads the top 57×57, the slot's tail is ignored -> we pad with zeros).
FORMATS: list[tuple[int, int, int, int]] = [
    (1010, 240, 240, 115200),   # Now Playing
    (1013, 50, 50, 5000),
    (1015, 58, 58, 6728),
    (1016, 57, 57, 6612),
]
FORMAT_IDS = [f[0] for f in FORMATS]

# Atom templates (MHII_HEADER/MHNI/STRMHOD/MHOD_*/MHFD/MHL*/MHIF_ALL) — real
# bytes from the iTunes reference, see ipodsync/_art_templates.py. We only patch image_id/
# song_id (in mhii) and ithmb_offset (in mhni).

MHFD_HDR = 132
MHSD_HDR = 96
MHL_HDR = 92
MHII_LEN = 928
FIRST_IMAGE_ID = 101


# --- encoding a cover to RGB565-LE ----------------------------------------------
def to_rgb565(image_bytes: bytes, width: int, height: int, slot: int) -> bytes:
    """Resize the cover to width×height, pack into RGB565-LE, pad to slot."""
    from PIL import Image

    im = Image.open(io.BytesIO(image_bytes)).convert("RGB").resize(
        (width, height), Image.LANCZOS)
    rgb = im.tobytes()  # width*height*3
    out = bytearray(width * height * 2)
    j = 0
    for i in range(0, len(rgb), 3):
        v = ((rgb[i] >> 3) << 11) | ((rgb[i + 1] >> 2) << 5) | (rgb[i + 2] >> 3)
        out[j] = v & 0xFF
        out[j + 1] = v >> 8
        j += 2
    if len(out) < slot:
        out.extend(b"\x00" * (slot - len(out)))
    return bytes(out)


def encode_cover(image_bytes: bytes) -> dict[int, bytes]:
    """Cover -> {format_id: rgb565_slot_bytes} for all 4 formats."""
    return {fid: to_rgb565(image_bytes, w, h, slot) for fid, w, h, slot in FORMATS}


# --- ArtworkDB model (surgical parse/build) -------------------------------------
@dataclass
class ArtworkDB:
    """A parsed ArtworkDB. Existing records are kept as raw bytes."""
    mhii_blocks: list[bytes] = field(default_factory=list)   # raw mhii (verbatim)
    song_ids: set[int] = field(default_factory=set)          # already covered (unsigned)
    next_id: int = FIRST_IMAGE_ID
    mhsd_album: bytes = b""    # the whole mhsd(index=2) verbatim (or we synthesize it)
    mhsd_file: bytes = b""     # the whole mhsd(index=3) verbatim (or we synthesize it)

    @classmethod
    def load(cls, path: str | Path) -> "ArtworkDB":
        p = Path(path)
        if not p.exists():
            return cls.empty()
        return cls.parse(p.read_bytes())

    @classmethod
    def empty(cls) -> "ArtworkDB":
        mhsd_album = _mhsd(2, MHSD_HDR + len(MHLA_TEMPLATE)) + MHLA_TEMPLATE
        mhlf = MHLF_TEMPLATE + MHIF_ALL
        mhsd_file = _mhsd(3, MHSD_HDR + len(mhlf)) + mhlf
        return cls(next_id=FIRST_IMAGE_ID, mhsd_album=mhsd_album, mhsd_file=mhsd_file)

    @classmethod
    def parse(cls, data: bytes) -> "ArtworkDB":
        if data[:4] != b"mhfd":
            raise ValueError("not an ArtworkDB (no mhfd header)")
        next_id = _i32(data, 28)
        o = MHFD_HDR
        mhii_blocks: list[bytes] = []
        song_ids: set[int] = set()
        mhsd_album = mhsd_file = b""
        n_mhsd = _i32(data, 20)
        for _ in range(n_mhsd):
            total = _i32(data, o + 8)
            index = struct.unpack_from("<h", data, o + 12)[0]
            block = data[o:o + total]
            if index == 1:  # image list: mhsd → mhli → mhii*
                mhli_off = MHSD_HDR
                num = _i32(block, mhli_off + 8)
                q = mhli_off + MHL_HDR
                for _i in range(num):
                    mtot = _i32(block, q + 8)
                    mhii = block[q:q + mtot]
                    mhii_blocks.append(mhii)
                    song_ids.add(struct.unpack_from("<Q", mhii, 20)[0])
                    q += mtot
            elif index == 2:
                mhsd_album = block
            elif index == 3:
                mhsd_file = block
            o += total
        if not mhsd_album:
            mhsd_album = _mhsd(2, MHSD_HDR + len(MHLA_TEMPLATE)) + MHLA_TEMPLATE
        if not mhsd_file:
            mhlf = MHLF_TEMPLATE + MHIF_ALL
            mhsd_file = _mhsd(3, MHSD_HDR + len(mhlf)) + mhlf
        return cls(mhii_blocks, song_ids, next_id, mhsd_album, mhsd_file)

    def has(self, song_id: int) -> bool:
        return (song_id % U64) in self.song_ids

    def add_record(self, song_id: int, offsets: dict[int, int]) -> int:
        """Add an mhii for a track. offsets: {format_id: ithmb_offset}. -> image_id."""
        song_id %= U64
        image_id = self.next_id
        self.mhii_blocks.append(_build_mhii(image_id, song_id, offsets))
        self.song_ids.add(song_id)
        self.next_id += 1
        return image_id

    def serialize(self) -> bytes:
        mhii_all = b"".join(self.mhii_blocks)
        n = len(self.mhii_blocks)
        mhli = bytearray(MHLI_TEMPLATE)
        struct.pack_into("<i", mhli, 8, n)
        mhsd_img = _mhsd(1, MHSD_HDR + MHL_HDR + len(mhii_all)) + bytes(mhli) + mhii_all

        total = MHFD_HDR + len(mhsd_img) + len(self.mhsd_album) + len(self.mhsd_file)
        mhfd = bytearray(MHFD_TEMPLATE)
        struct.pack_into("<i", mhfd, 8, total)
        struct.pack_into("<i", mhfd, 20, 3)          # num_children
        struct.pack_into("<i", mhfd, 28, self.next_id)
        return bytes(mhfd) + mhsd_img + self.mhsd_album + self.mhsd_file


def _i32(b, o):
    return struct.unpack_from("<i", b, o)[0]


def _mhsd(index: int, total: int) -> bytes:
    b = bytearray(MHSD_HDR)
    b[0:4] = b"mhsd"
    struct.pack_into("<i", b, 4, MHSD_HDR)
    struct.pack_into("<i", b, 8, total)
    struct.pack_into("<h", b, 12, index)
    return bytes(b)


def _build_mhii(image_id: int, song_id: int, offsets: dict[int, int]) -> bytes:
    hdr = bytearray(MHII_HEADER)
    struct.pack_into("<i", hdr, 16, image_id)
    struct.pack_into("<Q", hdr, 20, song_id % U64)
    body = bytearray()
    for fid in FORMAT_IDS:
        body += MHOD_CONTAINER
        mhni = bytearray(MHNI[fid])
        struct.pack_into("<i", mhni, 20, offsets[fid])
        body += mhni
        body += STRMHOD[fid]
    body += MHOD_MHAF
    out = bytes(hdr) + bytes(body)
    assert len(out) == MHII_LEN, f"mhii len {len(out)} != {MHII_LEN}"
    return out


# --- appending to .ithmb --------------------------------------------------------
def append_thumb(artwork_dir: Path, format_id: int, slot_bytes: bytes) -> int:
    """Append a frame to F<fmt>_1.ithmb. Returns ithmb_offset (bytes from the start)."""
    path = Path(artwork_dir) / f"F{format_id}_1.ithmb"
    offset = path.stat().st_size if path.exists() else 0
    with open(path, "ab") as f:
        f.write(slot_bytes)
    return offset


# --- high-level operation -------------------------------------------------------
def attach_cover(artwork_dir: str | Path, song_id: int, cover_bytes: bytes) -> int | None:
    """Attach a cover to a track (song_id = unsigned pid).

    Appends 4 thumbnails to .ithmb and an mhii to ArtworkDB (incrementally,
    without breaking what exists). Returns the image_id for item.artwork_cache_id,
    or None if the track already has a cover (we don't repeat).
    """
    artwork_dir = Path(artwork_dir)
    artwork_dir.mkdir(parents=True, exist_ok=True)
    db_path = artwork_dir / "ArtworkDB"
    db = ArtworkDB.load(db_path)
    if db.has(song_id):
        return None

    slots = encode_cover(cover_bytes)
    offsets = {fid: append_thumb(artwork_dir, fid, slots[fid]) for fid in FORMAT_IDS}
    image_id = db.add_record(song_id, offsets)

    tmp = db_path.with_suffix(".tmp")
    tmp.write_bytes(db.serialize())
    tmp.replace(db_path)
    return image_id


# --- extracting the embedded cover from audio -----------------------------------
def extract_embedded_cover(audio_path: str | Path) -> bytes | None:
    """Extract the embedded cover bytes from MP3 (APIC) or M4A (covr)."""
    p = Path(audio_path)
    ext = p.suffix.lower()
    try:
        if ext == ".mp3":
            from mutagen.id3 import ID3
            apic = ID3(p).getall("APIC")
            return apic[0].data if apic else None
        if ext in (".m4a", ".mp4", ".aac", ".alac"):
            from mutagen.mp4 import MP4
            covr = MP4(p).tags.get("covr") if MP4(p).tags else None
            return bytes(covr[0]) if covr else None
    except Exception:
        return None
    return None
