#!/usr/bin/env python3
"""Build src/ipodsync/_hashab_gen2.py (generate_key_material + generate_initial_buffer).

Dense straight-line blocks are transpiled (transpile_hashab.emit_statements),
control-flow constructs and pointer idioms (`*p`, `&arr[k]`, byte reinterpret)
are expanded by hand here. Validated against instrumented C.

    python tools/build_gen2.py <hashab_src_dir>
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from transpile_hashab import emit_statements, transpile_expr  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "ipodsync" / "_hashab_gen2.py"


def slice_between(s: str, start: str, end: str, frm: int = 0) -> tuple[str, int, int]:
    i = s.index(start, frm)
    j = s.index(end, i + len(start))
    return s[i + len(start):j], i, j


def body(lines: list[str], indent: str, narrow=None, byte_arrays=()) -> str:
    return "\n".join(emit_statements("\n".join(lines) + ";", indent, narrow, byte_arrays))


HEADER = '''"""generate_key_material + generate_initial_buffer (hand-port from dstaley/hashab).

GENERATED by tools/build_gen2.py — do not edit by hand. Dense blocks are
transpiled, control-flow constructs/pointers are expanded. 32-bit semantics are
handled by U32 (_hashab_gen_rt). Validated against instrumented C
(tests/test_hashab_port.py) and 100 hashAB vectors.
"""
from importlib import resources
import struct

from ._hashab_gen import generate_buffer_from_state_mixing as _gbsm
from ._hashab_gen_rt import (U32, BYTE1, BYTE2, HIBYTE, LOBYTE, LOWORD, HIWORD,
                             u8c, i8c, u16c, i16c)
from ._hashab_tables import TABLES

_BLOB = resources.files(__package__).joinpath("_hashab_tables.bin").read_bytes()


def _t(name):
    off, ln = TABLES[name]
    return _BLOB[off:off + ln]


GEN190_SBOX = _t("GEN190_SBOX")
GEN190_STATE_TABLE = _t("GEN190_STATE_TABLE")
IBUFF_KEY_TABLE = _t("IBUFF_KEY_TABLE")
IBUFF_MIX_SEED_A = _t("IBUFF_MIX_SEED_A")
IBUFF_MIX_SEED_B = _t("IBUFF_MIX_SEED_B")

INIT_CONST = [U32(x) for x in (0x2a0ed355, -0x1557e0ef, -0x54be9533, 0x6bdab689,
    0x2c740245, -0x12f2b1ff, -0x52596643, 0x6e3fe579, 0x2ed93135, -0x108d830f,
    -0x4ff43753, 0x70a51469, 0x313e6025, -0xe28541f, -0x4d8f0863, 0)]


def _u32_list(blob, n):
    return [U32(x) for x in struct.unpack(f"<{n}I", blob[:n * 4])]


def read_state_table(offset):
    return U32(GEN190_STATE_TABLE[int(offset) & 2047])


def read_sbox(idx):
    return U32(GEN190_SBOX[int(idx) & 2047])


def read_u32(tab, offset):
    o = int(offset)
    return U32(struct.unpack_from("<I", bytes(tab), o)[0])


def idx64(x):
    return int((-U32(19) * x + U32(69)) & U32(0x3f))


def xform_v318(v):
    return i8c(v - U32(116) - ((U32(2) * v + U32(14)) & U32(0xa)))


def mix_byte(x):
    return i8c(U32(94) * ((-U32(65) * x) & U32(0xda)) - U32(17) * x - U32(75))


def read316(v):
    return -U32(0x35d1732d) * v - U32(0x6448adfb)


def read317(v):
    return U32(0x2bf06481) * v - U32(0x7dbb7ad1)


def v318_mask(v):
    return (U32(2) * v + U32(0x3845070e)) & U32(0x842fbc0a)


def read318(v):
    return v - v318_mask(v)


def read318_off(v):
    return v - U32(0x21c59e74) - v318_mask(v)
'''


def build_gkm(src: str) -> str:
    out = ["\n\ndef generate_key_material(a1):",
           "    # a1: phase1_output (80 bytes). -> expanded_buffer (190 bytes).",
           "    v205 = [U32(0)] * 16",
           "    v187 = [U32(0)] * 16",
           "    v196 = [U32(0)] * 16",
           "    v228 = [U32(0)] * 9",
           "    v229_arr = [U32(0)] * 32",
           "    v211_v212 = bytearray(320)",
           '    v228[0] = U32(int.from_bytes(b"YC\\n\\x73"[::-1] if False else b"YC\\ns", "little"))',
           ""]
    # v228[0] = "YC\ns" LE
    out[-2] = '    v228[0] = U32(int.from_bytes(b"YC\\ns", "little"))'

    # --- stage 1: v2-loop ---
    v2blk, _, e = slice_between(src, "int v2 = 0;\n  do {", "} while (v2 != 6);")
    v2blk = v2blk.replace("v205[v2++]", "v205[v2]")
    out.append("    for v2 in range(6):")
    out.append(body(v2blk.strip().split("\n"), "        "))
    out.append("    for chunk_idx in range(5):")
    out.append("        base = chunk_idx * 4")
    out.append("        v205[6 + chunk_idx] = process_input_chunk(a1[base], a1[base+1], a1[base+2], a1[base+3])")
    out.append("    v205[11] = v205[13] = v205[14] = v205[15] = U32(-0x166dca43)")
    out.append("    v205[12] = U32(-0x166dca3f)")
    out.append("")

    # --- stage 2: while(1) ---
    out.append("    v172 = 0")
    out.append("    while True:")
    # v56 do-while over v205
    v56blk, _, _ = slice_between(src, "do {\n      int32_t curVal = *v56;",
                                 "v56 += 1;\n    } while (v56 != loop_end);")
    v56blk = ("int32_t curVal = *v56;" + v56blk).replace("*v56", "v205[_i]")
    out.append("        for _i in range(16):")
    out.append(body(v56blk.strip().split("\n"), "            "))
    out.append("        v196 = list(INIT_CONST)")
    out.append("        v196[15] = v228[0]")
    # i/j loops
    jblk, _, _ = slice_between(src, "for (int j = 0; j != 16; j++) {", "\n      }\n    }")
    jblk = jblk.replace("v196_arr[j]", "v196[j]")
    out.append("        for _i3 in range(3):")
    out.append("            _gbsm(v205, v196)")
    out.append("            for j in range(16):")
    out.append(body(jblk.strip().split("\n"), "                "))
    out.append("        _gbsm(v205, v196)")
    out.append("        for v91 in range(8):")
    out.append("            v229_arr[v91] = -U32(0x7095510b) * v196[8 + v91] + U32(0x1a313b21)")
    # v174 loop
    v174blk, _, _ = slice_between(src, "  do {\n      int32_t* v229_local = v229_arr;",
                                  "  } while (v91 != 8);")
    # body up to the v174 writes
    pre = v174blk.split("v174[4 * v91]")[0]
    pre = pre.replace("int v92 = -0x79cf6773 * v229_local[v91]",
                      "int v92 = -0x79cf6773 * v229_arr[v91]")
    out.append("        for v91 in range(8):")
    out.append(body(pre.strip().split("\n"), "            "))
    # 4 byte writes into v211_v212[32*v172 + 4*v91 + k]
    outs = re.findall(r"v174\[4 \* v91\+?\+? \+? ?(\d)?\] = ([^;]+);", v174blk)
    # simpler: extract the 4 expressions in order
    w = re.findall(r"v174\[4 \* v91(?:\+\+)?(?: \+ (\d))?\] = ([^;]+);", v174blk)
    for k, (idx, expr) in enumerate(w):
        expr = expr.replace("v91++", "v91")
        pe = transpile_expr(expr)
        out.append(f"            v211_v212[32 * v172 + 4 * v91 + {k}] = int(u8c({pe})) & 0xFF")
    out.append("        v172 += 1")
    out.append("        if v172 == 5:")
    out.append("            break")
    out.append("        v95 = U32(-0x166dca47)")
    out.append("        if v172 != 4:")
    out.append("            v95 = U32(v172) - U32(0x166dca43)")
    out.append("        v205[11] = v95")
    out.append("")

    # --- stage 3: v187 init + v96 do-while ---
    out.append("    for _i in range(16):")
    out.append("        v187[_i] = U32(0x14243245) * read_u32(GEN190_STATE_TABLE, _i * 4) - U32(0x3f7784fd)")
    out.append("    v205[11] = U32(-0x166dca46)")
    v96blk, _, _ = slice_between(src, "  do {\n    int32_t v97_val = *v96;",
                                 "v96 = v173 + 1;\n    v173 = v96;\n  } while (v96 != loop_end2);")
    v96blk = ("int32_t v97_val = *v96;" + v96blk).replace("*v96", "v205[_i]").replace("*v173", "v205[_i]")
    out.append("    for _i in range(16):")
    out.append(body(v96blk.strip().split("\n"), "        "))
    out.append("")

    # --- stage 4: gbsm ---
    out.append("    _gbsm(v205, v187)")

    # --- stage 5: k-loop + n-loops ---
    mblk, _, _ = slice_between(src, "for (int m = 0; m != 16; v185 = m) {",
                               "m = v185 + 1;\n    }")
    mblk = mblk.replace("v187_arr[m]", "v187[m]").replace("v205[v185]", "v205[m]").replace("v185", "m")
    out.append("    for _k in range(3):")
    out.append("        for m in range(16):")
    out.append(body(mblk.strip().split("\n"), "            "))
    out.append("        _gbsm(v205, v187)")
    out.append("    for _i in range(8):")
    out.append("        v228[_i + 1] = v187[_i + 8]")
    out.append("        v229_arr[_i] = -U32(0x7095510b) * v187[_i + 8] + U32(0x1a313b21)")
    # n-loop 1 (32): writes v212[4n+191..194] = v211_v212[4n+192..195]
    n1blk, _, _ = slice_between(src, "for (int n = 0; n != 32; n++) {", "\n  }\n\n  for (int n = 0; n != 30")
    out.append("    for n in range(32):")
    out.append("        _lo229 = int(v229_arr[n]) & 0xFF")
    # replace *(((uint8_t*)v229_arr) + 4 * n) with _lo229; v164 is derived from v229_arr[n]
    n1 = n1blk.replace("*(((uint8_t*)v229_arr) + 4 * n)", "_lo229")
    # rewrite v212[4*n+K] as v211_v212[4*n+K+1]
    n1 = re.sub(r"v212\[4 \* n \+ (\d+)\]",
                lambda m: f"__V212__[4 * n + {int(m.group(1)) + 1}]", n1)
    out.append(body(n1.strip().split("\n"), "        ", byte_arrays={"__V212__"}))
    # n-loop 2 (30): v212[n+159] = f(v212[n+191]) -> v211_v212[n+160] = f(v211_v212[n+192])
    n2blk, _, _ = slice_between(src, "for (int n = 0; n != 30; n++) {", "\n  }\n\n  __builtin_memcpy(output")
    n2 = re.sub(r"v212\[n \+ (\d+)\]",
                lambda m: f"__V212__[n + {int(m.group(1)) + 1}]", n2blk)
    out.append("    for n in range(30):")
    out.append(body(n2.strip().split("\n"), "        ", byte_arrays={"__V212__"}))
    out.append("    return bytes(v211_v212[0:190])")
    result = "\n".join(out)
    result = result.replace("__V212__", "v211_v212")
    return result


def _helper_loop(src, start_anchor, end_anchor, idxexpr, name, args):
    """mix_with_*/fold: for body with *out -> a1[idxexpr]."""
    blk, _, _ = slice_between(src, start_anchor, end_anchor)
    blk = blk.replace("result++", "result").replace("*out", f"a1[{idxexpr}]")
    lines = [f"\n\ndef {name}({args}):"]
    if "result" in idxexpr:
        lines.append("    for result in range(128):")
        ind = "        "
    else:
        lines.append("    for i in range(64):")
        ind = "        "
    lines.append(body(blk.strip().split("\n"), ind, byte_arrays={"a1"}))
    return "\n".join(lines)


def build_gib(src: str) -> str:
    out = ["\n\ndef generate_initial_buffer(a2):",
           "    # a2: expanded_buffer (190). -> ibuff_result (16 bytes).",
           "    a1 = bytearray(16)",
           "    v318 = _u32_list(IBUFF_MIX_SEED_A, 64) + [U32(0)] * 6",
           "    v317 = _u32_list(IBUFF_MIX_SEED_B, 64)",
           "    v316 = _u32_list(IBUFF_KEY_TABLE, 64)",
           "    v315 = [U32(0)] * 128",
           ""]
    # loop1: for (unsigned i=0; i!=512; i+=4) { ... v315[i/4]=...; }
    l1, _, _ = slice_between(src, "for (unsigned int i = 0; i != 512; i += 4) {",
                             "v315[i / 4] = ")
    l1last, _, _ = slice_between(src, "v315[i / 4] = ", ";\n  }")
    out.append("    for i in range(0, 512, 4):")
    out.append(body(l1.strip().split("\n"), "        "))
    out.append("        v315[i // 4] = " + transpile_expr(l1last.strip()))
    out.append("")
    # loop2: for (int j=0; j!=512; ++j) { ... v315[v303]=...; }
    l2, _, _ = slice_between(src, "for (int j = 0; j != 512; ++j) {", "\n  }\n\n  int8_t v249")
    out.append("    for j in range(512):")
    out.append(body(l2.strip().split("\n"), "        "))
    out.append("")
    # middle block: from "int8_t v249" to "mix_with_v318(a1, v318);"
    mid, _, _ = slice_between(src, "\n  int8_t v249", "\n  mix_with_v318(a1, v318);")
    out.append(body(("int8_t v249" + mid).strip().split("\n"), "    ", byte_arrays={"a1"}))
    out.append("    mix_with_v318(a1, v318)")
    out.append("    mix_with_v317(a1, v317)")
    out.append("    fold_v315_into_output(a1, v315)")
    out.append("    return bytes(a1)")
    return "\n".join(out)


def main() -> int:
    srcdir = Path(sys.argv[1])
    gkm_src = (srcdir / "generate_key_material.c").read_text()
    gkm_src = re.sub(r"/\*.*?\*/", "", gkm_src, flags=re.DOTALL)
    gib_src = (srcdir / "generate_initial_buffer.c").read_text()
    gib_src = re.sub(r"/\*.*?\*/", "", gib_src, flags=re.DOTALL)

    text = HEADER
    # process_input_chunk
    pic = slice_between(gkm_src, "process_input_chunk(uint8_t byte0, uint8_t byte1, uint8_t byte2, uint8_t byte3) {", "\n}")[0]
    pic_stmts, pic_ret = pic.rsplit("return", 1)
    text += "\n\ndef process_input_chunk(byte0, byte1, byte2, byte3):\n"
    text += body(pic_stmts.strip().split("\n"), "    ") + "\n"
    text += "    return " + transpile_expr(pic_ret.strip().rstrip(";")) + "\n"
    text += build_gkm(gkm_src)
    # gib helpers
    text += _helper_loop(gib_src,
                         "mix_with_v318(uint8_t* a1, uint32_t* v318) {\n  for (int i = 0; i != 64; ++i) {",
                         "\n  }\n}", "i & 0xf", "mix_with_v318", "a1, v318")
    text += _helper_loop(gib_src,
                         "mix_with_v317(uint8_t* a1, uint32_t* v317) {\n  for (int i = 0; i != 64; ++i) {",
                         "\n  }\n}", "i & 0xf", "mix_with_v317", "a1, v317")
    text += _helper_loop(gib_src, "int result = 0;\n  do {",
                         "  } while (result != 128);", "result & 0xf",
                         "fold_v315_into_output", "a1, v315")
    text += build_gib(gib_src)
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
