#!/usr/bin/env python3
"""Generate ipodsync/_art_templates.py from the iTunes reference ArtworkDB.

Extracts constant byte templates of atoms (mhii/mhni/string mhod/mhaf/
mhfd/mhl*/mhif) from native/fixtures/itunes_artwork/ArtworkDB. These templates are real
iTunes bytes; the artwork writer (ipodsync/artwork_writer.py) patches only
image_id/song_id/ithmb_offset into them. Run when the reference is updated.

    python scripts/gen_art_templates.py
"""
from __future__ import annotations

import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GOLDEN = ROOT / "tests" / "data" / "ArtworkDB"
OUT = ROOT / "src" / "ipodsync" / "_art_templates.py"


def main() -> int:
    d = GOLDEN.read_bytes()

    def i32(o):
        return struct.unpack_from("<i", d, o)[0]

    mhii = d.find(b"mhii")
    pieces = {
        "MHII_HEADER": d[mhii:mhii + 152],
        "MHOD_CONTAINER": d[mhii + 152:mhii + 152 + 24],
    }
    p = mhii + i32(mhii + 4)
    mhni, strm = {}, {}
    for _ in range(4):
        m = p + i32(p + 4)
        s = m + i32(m + 4)
        fid = i32(m + 16)
        mhni[fid] = d[m:m + 76]
        strm[fid] = d[s:s + 64]
        p += i32(p + 8)
    pieces["MHOD_MHAF"] = d[p:p + 120]
    pieces["MHFD_TEMPLATE"] = d[0:132]

    mhli = d.find(b"mhli")
    pieces["MHLI_TEMPLATE"] = d[mhli:mhli + 92]
    mhla = d.find(b"mhla")
    pieces["MHLA_TEMPLATE"] = d[mhla:mhla + 92]
    mhlf = d.find(b"mhlf")
    pieces["MHLF_TEMPLATE"] = d[mhlf:mhlf + 92]
    q = mhlf + i32(mhlf + 4)
    allmhif = b""
    for _ in range(6):
        allmhif += d[q:q + 124]
        q += i32(q + 8)
    pieces["MHIF_ALL"] = allmhif

    with open(OUT, "w") as f:
        f.write('"""Constant byte templates of nano 7G ArtworkDB atoms.\n\n'
                "Generated by scripts/gen_art_templates.py from the iTunes reference\n"
                "native/fixtures/itunes_artwork/ArtworkDB. Do not edit by hand —\n"
                "these are real iTunes bytes; the writer patches only "
                'image_id/song_id/ithmb_offset.\n"""\n\n')
        for k, v in pieces.items():
            f.write(f'{k} = bytes.fromhex("{v.hex()}")\n')
        f.write("\nMHNI = {\n")
        for fid in (1010, 1013, 1015, 1016):
            f.write(f'    {fid}: bytes.fromhex("{mhni[fid].hex()}"),\n')
        f.write("}\n\nSTRMHOD = {\n")
        for fid in (1010, 1013, 1015, 1016):
            f.write(f'    {fid}: bytes.fromhex("{strm[fid].hex()}"),\n')
        f.write("}\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
