#!/usr/bin/env python3
"""Generate ipodsync/_lib_templates.py from a full .itlp backup.

library.py adds a track by cloning an existing template row from the
item/artist/album/track_artist (Library.itdb) and location (Locations.itdb) tables.
On an empty (just-wiped) library these rows do not exist → add fails. Here we
take one template row from a NON-EMPTY backup and bake it in as a fallback.

We neutralize fields that must not be inherited from another track:
  - any artwork_* (otherwise a new track without artwork would inherit a foreign cache_id);
  - item.composer_pid -> 0 (a reference to a composer that does not exist in an empty db).

All pid/name/order/sizes are overwritten by add_track anyway.

    python scripts/gen_lib_templates.py [BACKUP_ITLP]
Default BACKUP: the newest non-empty ~/ipod-backups/itlp-*.
"""
from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ipodsync" / "_lib_templates.py"

# (db file, table, constant name)
SPECS = [
    ("Library.itdb", "item", "ITEM"),
    ("Library.itdb", "artist", "ARTIST"),
    ("Library.itdb", "album", "ALBUM"),
    ("Library.itdb", "track_artist", "TRACK_ARTIST"),
    ("Locations.itdb", "location", "LOCATION"),
]


def _newest_nonempty_backup() -> Path:
    cands = sorted(Path.home().glob("ipod-backups/itlp-*"), reverse=True)
    for b in cands:
        db = b / "Library.itdb"
        if not db.exists():
            continue
        c = sqlite3.connect(db)
        try:
            n = c.execute("SELECT COUNT(*) FROM item").fetchone()[0]
        except sqlite3.Error:
            n = 0
        finally:
            c.close()
        if n > 0:
            return b
    raise SystemExit("no non-empty backup ~/ipod-backups/itlp-* found")


def _neutralize(table: str, row: dict) -> dict:
    for k in list(row):
        if "artwork" in k:
            row[k] = 0 if isinstance(row[k], int) else None
    if table == "item":
        row["composer_pid"] = 0
    return row


def main() -> int:
    itlp = Path(sys.argv[1]) if len(sys.argv) > 1 else _newest_nonempty_backup()
    templates: dict[str, dict] = {}
    for dbname, table, const in SPECS:
        c = sqlite3.connect(itlp / dbname)
        c.row_factory = sqlite3.Row
        r = c.execute(f"SELECT * FROM {table} LIMIT 1").fetchone()
        c.close()
        if r is None:
            raise SystemExit(f"no template row in {itlp/dbname}:{table}")
        templates[const] = _neutralize(table, dict(r))

    with open(OUT, "w") as f:
        f.write('"""Template rows for adding a track to an EMPTY .itlp library.\n\n'
                f"Generated by scripts/gen_lib_templates.py from {itlp.name}.\n"
                "Do not edit by hand. Used by library.py as a fallback when the\n"
                "table is empty (a freshly-wiped library). artwork_*/composer_pid are zeroed.\n"
                '"""\n\n')
        for const, row in templates.items():
            f.write(f"{const}_TEMPLATE = {row!r}\n\n")
    print(f"wrote {OUT} from {itlp.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
