#!/usr/bin/env python3
"""Extract white-box AES tables from the dstaley/hashab C source into a binary blob.

All `data/*.c` declare `const uint8_t NAME[N] = { ... };`. We pack their bytes
into a single `_hashab_tables.bin` + a Python manifest `_hashab_tables.py` (name -> (off,len)).
The data is public domain (Unlicense); the C source is not part of the OSS repo — only the blob.

    python tools/gen_hashab_tables.py /path/to/hashab/src
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_BIN = ROOT / "src" / "ipodsync" / "_hashab_tables.bin"
OUT_PY = ROOT / "src" / "ipodsync" / "_hashab_tables.py"

DECL = re.compile(r"const\s+uint8_t\s+(\w+)\s*\[\s*(\d+)\s*\]\s*=\s*\{(.*?)\}\s*;",
                  re.DOTALL)
INT = re.compile(r"0[xX][0-9a-fA-F]+|\d+")


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: gen_hashab_tables.py /path/to/hashab/src"); return 2
    data_dir = Path(sys.argv[1]) / "data"
    tables: dict[str, bytes] = {}
    for cfile in sorted(data_dir.glob("*.c")):
        text = cfile.read_text()
        for m in DECL.finditer(text):
            name, size, body = m.group(1), int(m.group(2)), m.group(3)
            vals = [int(x, 0) & 0xFF for x in INT.findall(body)]
            if len(vals) != size:
                raise SystemExit(f"{name}: {len(vals)} bytes != declared {size}")
            tables[name] = bytes(vals)

    blob = bytearray()
    manifest: dict[str, tuple[int, int]] = {}
    for name in sorted(tables):
        manifest[name] = (len(blob), len(tables[name]))
        blob += tables[name]
    OUT_BIN.write_bytes(bytes(blob))

    lines = ['"""hashAB tables manifest: name -> (offset, length) in _hashab_tables.bin.\n\n'
             "Generated by tools/gen_hashab_tables.py from dstaley/hashab (public domain).\n"
             'The bytes are loaded by hashab_py.py via importlib.resources.\n"""\n']
    lines.append("TABLES = {")
    for name, (off, ln) in manifest.items():
        lines.append(f"    {name!r}: ({off}, {ln}),")
    lines.append("}")
    OUT_PY.write_text("\n".join(lines) + "\n")

    print(f"tables: {len(tables)}, blob: {len(blob)} bytes ({len(blob)/1024:.0f} KiB)")
    for name, (off, ln) in manifest.items():
        print(f"  {name:<20} {ln}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
